name: fairway
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  google_fonts: ^6.2.1
  hive_flutter: ^1.1.0
  get_it: ^8.0.3
  equatable: ^2.0.7
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.1
  firebase_messaging: ^15.2.1
  firebase_storage: ^12.4.1
  cloud_firestore: ^5.6.2
  cloud_functions: ^5.3.1
  loading_animation_widget: ^1.3.0
  firebase_remote_config: ^5.3.1
  connectivity_plus: ^6.1.2
  shared_preferences: ^2.4.0
  sign_in_with_apple: ^6.1.4
  flutter_native_splash: ^2.4.4
  photo_manager: ^3.6.4
  flutter_phoenix: ^1.1.1
  permission_handler: ^11.4.0
  go_router: ^14.8.1
  logger: ^2.5.0
  toastification: ^2.3.0
  flutter_svg: ^2.0.17
  cached_network_image: ^3.4.1
  dio: ^5.8.0+1
  smooth_page_indicator: ^1.2.1
  geolocator: ^13.0.3
  geocoding: ^3.0.0
  url_launcher: ^6.3.1

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  intl_utils: ^2.8.8
  hive_generator: ^2.0.1
  very_good_analysis: ^7.0.0
  build_runner: ^2.4.14

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/svgs/
    - assets/images/
  fonts:
    - family: Gothic
      fonts:
        - asset: assets/fonts/Fontspring-DEMO-allroundgothic-book.otf
          weight: 400
        - asset: assets/fonts/Fontspring-DEMO-allroundgothic-bookoblique.otf
          weight: 400
          style: italic
        - asset: assets/fonts/Fontspring-DEMO-allroundgothic-medium.otf
          weight: 500
        - asset: assets/fonts/Fontspring-DEMO-allroundgothic-mediumoblique.otf
          weight: 500
          style: italic
        - asset: assets/fonts/Fontspring-DEMO-allroundgothic-semi.otf
          weight: 600
        - asset: assets/fonts/Fontspring-DEMO-allroundgothic-semioblique.otf
          weight: 600
          style: italic
        - asset: assets/fonts/Fontspring-DEMO-allroundgothic-bold.otf
          weight: 700
        - asset: assets/fonts/Fontspring-DEMO-allroundgothic-boldoblique.otf
          weight: 700
          style: italic
        - asset: assets/fonts/Fontspring-DEMO-allroundgothic-lig.otf
          weight: 300
        - asset: assets/fonts/Fontspring-DEMO-allroundgothic-ligoblique.otf
          weight: 300
          style: italic
        - asset: assets/fonts/Fontspring-DEMO-allroundgothic-text.otf
          weight: 400
        - asset: assets/fonts/Fontspring-DEMO-allroundgothic-textoblique.otf
          weight: 400
          style: italic
        - asset: assets/fonts/Fontspring-DEMO-allroundgothic-thick.otf
          weight: 800
        - asset: assets/fonts/Fontspring-DEMO-allroundgothic-thickoblique.otf
          weight: 800
          style: italic
        - asset: assets/fonts/Fontspring-DEMO-allroundgothic-xlig.otf
          weight: 200
        - asset: assets/fonts/Fontspring-DEMO-allroundgothic-xligoblique.otf
          weight: 200
          style: italic
