import 'package:fairway/app/view/splash_screen.dart';
import 'package:fairway/fairway/features/home/presentation/view/home_screen.dart';
import 'package:fairway/fairway/features/home/presentation/view/search_screen.dart';
import 'package:fairway/fairway/features/location/presentation/view/select_location.dart';
import 'package:fairway/fairway/features/location/presentation/view/user_location.dart';
import 'package:fairway/fairway/features/onboarding_flow/presentation/view/forgot_password_screen.dart';
import 'package:fairway/fairway/features/onboarding_flow/presentation/view/intro_screen.dart';
import 'package:fairway/fairway/features/onboarding_flow/presentation/view/password_code_screen.dart';
import 'package:fairway/fairway/features/onboarding_flow/presentation/view/password_recovered.dart';
import 'package:fairway/fairway/features/onboarding_flow/presentation/view/reset_password_screen.dart';
import 'package:fairway/fairway/features/onboarding_flow/presentation/view/sign_in_screen.dart';
import 'package:fairway/fairway/features/onboarding_flow/presentation/view/sign_up_screen.dart';
import 'package:fairway/fairway/features/profile/presentation/view/account_information.dart'
    show AccountInformationScreen;
import 'package:fairway/fairway/features/profile/presentation/view/change_password.dart';
import 'package:fairway/fairway/features/profile/presentation/view/profile_screen.dart';
import 'package:flutter/cupertino.dart';
import 'package:go_router/go_router.dart';

part 'router.dart';
part 'routes.dart';
